//! Emit TypeScript view types from JSON lens files via panproto protolens.
//!
//! Reads lens files from packages/lenses/, converts steps to ProtolensChain
//! using panproto combinators, instantiates against Lexicon schemas to produce
//! target schemas, and walks the target to emit TypeScript interfaces.

use panproto_gat::Name;
use panproto_protocols::emit::children_by_edge;
use panproto_schema::{Protocol, Schema};

/// Emit all TypeScript view types from JSON lens files.
pub fn emit_all_views_from_lenses(
    schemas: &[(Schema, String)],
    lenses: &[crate::lens_config::LensFile],
) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by cospan-codegen via panproto protolens (from JSON lens files).\n");
    out.push_str("// Source: packages/lenses/*.lens.json\n");
    out.push_str("// Do not edit manually.\n\n");

    for lens in crate::lens_config::db_projection_lenses(lenses) {
        if let Some((schema, _)) = schemas.iter().find(|(_, nsid)| nsid == &lens.source) {
            let body_id = find_record_body(schema, &lens.source);
            let chain = crate::lens_config::steps_to_protolens_chain(&lens.steps, &body_id);
            let protocol = Protocol::default();
            let target = match chain.instantiate(schema, &protocol) {
                Ok(l) => l.tgt_schema,
                Err(e) => {
                    eprintln!("  warn: lens instantiation for {}: {e:?}", lens.source);
                    schema.clone()
                }
            };

            let table = lens.table.as_ref();
            let view_name = table
                .map(|t| {
                    t.row_struct
                        .strip_suffix("Row")
                        .unwrap_or(&t.row_struct)
                        .to_string()
                        + "View"
                })
                .unwrap_or_else(|| nsid_to_pascal(&lens.source) + "View");
            let include_did = table.map(|t| t.include_did).unwrap_or(true);
            let include_rkey = table.map(|t| t.include_rkey).unwrap_or(true);
            let empty_defaults = std::collections::HashMap::new();
            let column_defaults = table
                .map(|t| &t.column_defaults)
                .unwrap_or(&empty_defaults);

            out.push_str(&emit_view(
                &target,
                &lens.source,
                &view_name,
                include_did,
                include_rkey,
                column_defaults,
            ));
        }
    }

    // List response wrappers
    for (type_name, wrapper_key) in &[
        ("Repo", "repos"), ("Issue", "issues"), ("IssueComment", "comments"),
        ("Pull", "pulls"), ("PullComment", "comments"), ("Star", "stars"),
        ("Follow", "follows"), ("Node", "nodes"), ("Org", "orgs"),
        ("OrgMember", "members"), ("Collaborator", "collaborators"),
        ("RefUpdate", "refUpdates"), ("Label", "labels"),
        ("Pipeline", "pipelines"), ("Reaction", "reactions"),
    ] {
        out.push_str(&format!(
            "export interface {type_name}ListResponse {{\n  {wrapper_key}: {type_name}View[];\n  cursor: string | null;\n}}\n\n"
        ));
    }

    out
}

/// Emit a single TypeScript interface from a target schema.
fn emit_view(
    target: &Schema,
    nsid: &str,
    view_name: &str,
    include_did: bool,
    include_rkey: bool,
    column_defaults: &std::collections::HashMap<String, String>,
) -> String {
    let body_id = find_record_body(target, nsid);
    let mut out = String::new();
    out.push_str(&format!("// {nsid} (via lens file)\n"));
    out.push_str(&format!("export interface {view_name} {{\n"));

    if include_did { out.push_str("  did: string;\n"); }
    if include_rkey { out.push_str("  rkey: string;\n"); }

    // Fields from prop edges (surviving Lexicon fields)
    let props = children_by_edge(target, &body_id, "prop");
    for (edge, prop_vertex) in &props {
        let name = edge.name.as_ref().map(|n| n.as_str()).unwrap_or("unknown");
        let ts = vertex_kind_to_ts(&prop_vertex.kind);
        let required = is_field_required(target, &body_id, name);
        if required {
            out.push_str(&format!("  {name}: {ts};\n"));
        } else {
            out.push_str(&format!("  {name}: {ts} | null;\n"));
        }
    }

    // Fields added by add_field (appear as vertices without prop edges)
    let body_prefix = format!("{body_id}.");
    let prop_targets: std::collections::HashSet<String> =
        props.iter().map(|(_, v)| v.id.to_string()).collect();
    let mut extras: Vec<_> = target
        .vertices
        .iter()
        .filter(|(id, _)| {
            let s = id.to_string();
            s.starts_with(&body_prefix)
                && !s[body_prefix.len()..].contains('.')
                && !s[body_prefix.len()..].contains(':')
                && !prop_targets.contains(&s)
        })
        .collect();
    extras.sort_by_key(|(id, _)| id.to_string());

    for (id, v) in &extras {
        let name = id.as_str().strip_prefix(&body_prefix).unwrap_or(id.as_str());
        let ts = vertex_kind_to_ts(&v.kind);
        out.push_str(&format!("  {name}: {ts};\n"));
    }

    out.push_str("  indexedAt: string;\n");
    out.push_str("}\n\n");

    // Normalization function
    out.push_str(&format!(
        "export function normalize{view_name}(raw: Partial<{view_name}>): {view_name} {{\n"
    ));
    out.push_str("  return {\n");
    if include_did { out.push_str("    did: raw.did ?? '',\n"); }
    if include_rkey { out.push_str("    rkey: raw.rkey ?? '',\n"); }
    for (edge, prop_vertex) in &props {
        let name = edge.name.as_ref().map(|n| n.as_str()).unwrap_or("unknown");
        let required = is_field_required(target, &body_id, name);
        let def = if !required { "null" } else { kind_default(&prop_vertex.kind, name, column_defaults) };
        out.push_str(&format!("    {name}: raw.{name} ?? {def},\n"));
    }
    for (id, v) in &extras {
        let name = id.as_str().strip_prefix(&body_prefix).unwrap_or(id.as_str());
        let def = kind_default(&v.kind, name, column_defaults);
        out.push_str(&format!("    {name}: raw.{name} ?? {def},\n"));
    }
    out.push_str("    indexedAt: raw.indexedAt ?? '',\n");
    out.push_str("  };\n");
    out.push_str("}\n\n");

    out
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn find_record_body(schema: &Schema, nsid: &str) -> String {
    let children = children_by_edge(schema, nsid, "record-schema");
    if let Some((_, body)) = children.first() {
        return body.id.to_string();
    }
    let body_id = format!("{nsid}:body");
    if schema.has_vertex(&body_id) { return body_id; }
    nsid.to_string()
}

fn is_field_required(schema: &Schema, body_id: &str, field_name: &str) -> bool {
    schema
        .required
        .get(&Name::from(body_id))
        .map(|reqs| reqs.iter().any(|e| e.name.as_ref().map(|n| n.as_str()) == Some(field_name)))
        .unwrap_or(false)
}

fn vertex_kind_to_ts(kind: &Name) -> &'static str {
    match kind.as_str() {
        "string" | "cid-link" | "ref" | "token" | "bytes" => "string",
        "integer" | "number" | "float" => "number",
        "boolean" => "boolean",
        "array" => "unknown[]",
        "object" | "union" => "Record<string, unknown>",
        _ => { eprintln!("    warn: unhandled vertex kind '{kind}'"); "unknown" }
    }
}

fn kind_default(kind: &Name, field_name: &str, defaults: &std::collections::HashMap<String, String>) -> &'static str {
    if let Some(expr) = defaults.get(field_name) {
        return match expr.as_str() {
            "'open'" => "'open'", "'pending'" => "'pending'",
            "'public'" => "'public'", "'main'" => "'main'",
            "0" => "0", _ => "''",
        };
    }
    match kind.as_str() {
        "string" | "cid-link" | "ref" | "token" | "bytes" => "''",
        "integer" | "number" | "float" => "0",
        "boolean" => "false",
        _ => "''",
    }
}

fn nsid_to_pascal(nsid: &str) -> String {
    nsid.split('.').map(|s| {
        let mut c = s.chars();
        match c.next() {
            None => String::new(),
            Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        }
    }).collect()
}
