//! Cospan codegen: Lexicon JSON → Rust types + SQL DDL + TypeScript interfaces
//!
//! Reads all `dev.cospan.*` Lexicon JSON files from `packages/lexicons/`,
//! parses them via panproto's ATProto protocol, transforms the schemas
//! to target protocol schemas, and emits generated code.
//!
//! Generated output goes to `generated/` (gitignored).
//!
//! Usage: cargo run -p cospan-codegen

mod morphism;

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use panproto_protocols::web_document::atproto;
fn main() -> Result<()> {
    let workspace_root = find_workspace_root()?;
    let lexicons_dir = workspace_root.join("packages/lexicons");
    let generated_dir = workspace_root.join("generated");

    // Create output directories
    fs::create_dir_all(generated_dir.join("rust"))?;
    fs::create_dir_all(generated_dir.join("sql"))?;
    fs::create_dir_all(generated_dir.join("typescript"))?;

    // Discover all Lexicon JSON files
    let lexicon_files = discover_lexicons(&lexicons_dir)?;
    println!("Found {} Lexicon files", lexicon_files.len());

    let mut all_rust = String::new();
    let mut all_sql = String::new();
    let mut all_ts = String::new();

    all_rust.push_str("// Generated by cospan-codegen from packages/lexicons/\n");
    all_rust.push_str("// Do not edit manually.\n\n");
    all_rust.push_str("use serde::{Serialize, Deserialize};\n\n");

    all_sql.push_str("-- Generated by cospan-codegen from packages/lexicons/\n");
    all_sql.push_str("-- Do not edit manually.\n\n");

    all_ts.push_str("// Generated by cospan-codegen from packages/lexicons/\n");
    all_ts.push_str("// Do not edit manually.\n\n");

    for lexicon_path in &lexicon_files {
        let relative = lexicon_path.strip_prefix(&lexicons_dir).unwrap();
        println!("  Processing: {}", relative.display());

        let json_str = fs::read_to_string(lexicon_path)
            .with_context(|| format!("reading {}", lexicon_path.display()))?;
        let json: serde_json::Value = serde_json::from_str(&json_str)
            .with_context(|| format!("parsing JSON from {}", lexicon_path.display()))?;

        let nsid = json.get("id").and_then(|v| v.as_str()).unwrap_or("unknown");

        // Parse Lexicon → ATProto Schema
        let atproto_schema =
            atproto::parse_lexicon(&json).with_context(|| format!("parsing lexicon {nsid}"))?;

        // Transform ATProto Schema → Rust Schema → emit
        match morphism::atproto_to_rust(&atproto_schema, nsid) {
            Ok(rust_schema) => match morphism::emit_rust_types(&rust_schema) {
                Ok(rust_code) => {
                    all_rust.push_str(&format!("// {nsid}\n"));
                    all_rust.push_str(&rust_code);
                    all_rust.push('\n');
                }
                Err(e) => eprintln!("  warn: emit_rust_types for {nsid}: {e}"),
            },
            Err(e) => eprintln!("  warn: atproto_to_rust for {nsid}: {e}"),
        }

        // Transform ATProto Schema → SQL Schema → emit
        match morphism::atproto_to_sql(&atproto_schema, nsid) {
            Ok(sql_schema) => match morphism::emit_ddl(&sql_schema) {
                Ok(ddl) => {
                    all_sql.push_str(&format!("-- {nsid}\n"));
                    all_sql.push_str(&ddl);
                    all_sql.push_str("\n\n");
                }
                Err(e) => eprintln!("  warn: emit_ddl for {nsid}: {e}"),
            },
            Err(e) => eprintln!("  warn: atproto_to_sql for {nsid}: {e}"),
        }

        // Transform ATProto Schema → TypeScript Schema → emit
        match morphism::atproto_to_typescript(&atproto_schema, nsid) {
            Ok(ts_schema) => match morphism::emit_ts_types(&ts_schema) {
                Ok(ts_code) => {
                    all_ts.push_str(&format!("// {nsid}\n"));
                    all_ts.push_str(&ts_code);
                    all_ts.push('\n');
                }
                Err(e) => eprintln!("  warn: emit_ts_types for {nsid}: {e}"),
            },
            Err(e) => eprintln!("  warn: atproto_to_typescript for {nsid}: {e}"),
        }
    }

    // Write generated files
    fs::write(generated_dir.join("rust/types.rs"), &all_rust)?;
    fs::write(generated_dir.join("sql/schema.sql"), &all_sql)?;
    fs::write(generated_dir.join("typescript/types.ts"), &all_ts)?;

    println!("\nGenerated:");
    println!("  generated/rust/types.rs");
    println!("  generated/sql/schema.sql");
    println!("  generated/typescript/types.ts");

    Ok(())
}

fn discover_lexicons(dir: &Path) -> Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    walk_dir(dir, &mut files)?;
    files.sort();
    Ok(files)
}

fn walk_dir(dir: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    if !dir.exists() {
        anyhow::bail!("lexicons directory not found: {}", dir.display());
    }
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            walk_dir(&path, files)?;
        } else if path.extension().is_some_and(|e| e == "json") {
            files.push(path);
        }
    }
    Ok(())
}

fn find_workspace_root() -> Result<PathBuf> {
    let mut dir = std::env::current_dir()?;
    loop {
        if dir.join("Cargo.toml").exists() && dir.join("packages").exists() {
            return Ok(dir);
        }
        if !dir.pop() {
            anyhow::bail!("could not find workspace root (looking for Cargo.toml + packages/)");
        }
    }
}
