//! Cospan codegen: Lexicon JSON → Rust types + SQL DDL + TypeScript interfaces
//!
//! Reads all `dev.cospan.*` Lexicon JSON files from `packages/lexicons/`,
//! parses them via panproto's ATProto protocol, transforms the schemas
//! to target protocol schemas, and emits generated code.
//!
//! Generated output goes to `generated/` (gitignored).
//!
//! Usage: cargo run -p cospan-codegen
//!        cargo run -p cospan-codegen -- --check   # breaking change detection

mod emit_rows;
mod morphism;
mod record_config;

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use panproto_protocols::web_document::atproto;

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().collect();
    let check_mode = args.iter().any(|a| a == "--check");

    let workspace_root = find_workspace_root()?;
    let lexicons_dir = workspace_root.join("packages/lexicons");
    let generated_dir = workspace_root.join("generated");

    // Create output directories
    fs::create_dir_all(generated_dir.join("rust"))?;
    fs::create_dir_all(generated_dir.join("sql"))?;
    fs::create_dir_all(generated_dir.join("typescript"))?;

    // Discover all Lexicon JSON files
    let lexicon_files = discover_lexicons(&lexicons_dir)?;
    println!("Found {} Lexicon files", lexicon_files.len());

    // --- Breaking change detection (--check mode) ---
    if check_mode {
        return run_check_mode(&lexicon_files, &lexicons_dir, &generated_dir);
    }

    // --- Standard generation mode ---

    // Collect all parsed schemas for check baseline
    let mut schemas_for_baseline = Vec::new();

    let mut all_rust = String::new();
    let mut all_sql = String::new();
    let mut all_ts = String::new();
    let mut all_row_types = String::new();
    let mut all_crud = String::new();
    let mut all_from_json = String::new();

    // Headers
    all_rust.push_str("// Generated by cospan-codegen from packages/lexicons/\n");
    all_rust.push_str("// Do not edit manually.\n\n");
    all_rust.push_str("use serde::{Serialize, Deserialize};\n\n");

    all_sql.push_str("-- Generated by cospan-codegen from packages/lexicons/\n");
    all_sql.push_str("-- Do not edit manually.\n\n");

    all_ts.push_str("// Generated by cospan-codegen from packages/lexicons/\n");
    all_ts.push_str("// Do not edit manually.\n\n");

    all_row_types.push_str("// Generated by cospan-codegen from packages/lexicons/\n");
    all_row_types.push_str("// Do not edit manually.\n\n");
    all_row_types.push_str("use chrono::{DateTime, Utc};\nuse sqlx::PgPool;\nuse serde::{Serialize, Deserialize};\n\n");
    all_row_types.push_str(&emit_rows::emit_helper_functions());
    all_row_types.push('\n');

    all_crud.push_str("// Generated by cospan-codegen from packages/lexicons/\n");
    all_crud.push_str("// Do not edit manually.\n\n");
    all_crud.push_str("use chrono::{DateTime, Utc};\nuse sqlx::PgPool;\nuse super::types::*;\n\n");

    all_from_json.push_str("// Generated by cospan-codegen from packages/lexicons/\n");
    all_from_json.push_str("// Do not edit manually.\n\n");
    all_from_json.push_str("use super::types::*;\n\n");

    for lexicon_path in &lexicon_files {
        let relative = lexicon_path.strip_prefix(&lexicons_dir).unwrap();
        println!("  Processing: {}", relative.display());

        let json_str = fs::read_to_string(lexicon_path)
            .with_context(|| format!("reading {}", lexicon_path.display()))?;
        let json: serde_json::Value = serde_json::from_str(&json_str)
            .with_context(|| format!("parsing JSON from {}", lexicon_path.display()))?;

        let nsid = json.get("id").and_then(|v| v.as_str()).unwrap_or("unknown");

        // Parse Lexicon → ATProto Schema
        let atproto_schema =
            atproto::parse_lexicon(&json).with_context(|| format!("parsing lexicon {nsid}"))?;

        // Save for baseline
        schemas_for_baseline.push((nsid.to_string(), json.clone()));

        // --- Original outputs (Lexicon projection types) ---

        // Transform ATProto Schema → Rust Schema → emit
        match morphism::atproto_to_rust(&atproto_schema, nsid) {
            Ok(rust_schema) => match morphism::emit_rust_types(&rust_schema) {
                Ok(rust_code) => {
                    all_rust.push_str(&format!("// {nsid}\n"));
                    all_rust.push_str(&rust_code);
                    all_rust.push('\n');
                }
                Err(e) => eprintln!("  warn: emit_rust_types for {nsid}: {e}"),
            },
            Err(e) => eprintln!("  warn: atproto_to_rust for {nsid}: {e}"),
        }

        // Transform ATProto Schema → SQL Schema → emit
        match morphism::atproto_to_sql(&atproto_schema, nsid) {
            Ok(sql_schema) => match morphism::emit_ddl(&sql_schema) {
                Ok(ddl) => {
                    all_sql.push_str(&format!("-- {nsid}\n"));
                    all_sql.push_str(&ddl);
                    all_sql.push_str("\n\n");
                }
                Err(e) => eprintln!("  warn: emit_ddl for {nsid}: {e}"),
            },
            Err(e) => eprintln!("  warn: atproto_to_sql for {nsid}: {e}"),
        }

        // Transform ATProto Schema → TypeScript Schema → emit (with export)
        match morphism::atproto_to_typescript(&atproto_schema, nsid) {
            Ok(ts_schema) => match morphism::emit_ts_types(&ts_schema) {
                Ok(ts_code) => {
                    all_ts.push_str(&format!("// {nsid}\n"));
                    // Add export keyword
                    all_ts.push_str(&ts_code.replace("interface ", "export interface "));
                    all_ts.push('\n');
                }
                Err(e) => eprintln!("  warn: emit_ts_types for {nsid}: {e}"),
            },
            Err(e) => eprintln!("  warn: atproto_to_typescript for {nsid}: {e}"),
        }

        // --- New outputs (database Row types + CRUD + from_json) ---

        if let Some(config) = record_config::config_for_nsid(nsid) {
            // Row type
            match emit_rows::emit_row_types(&atproto_schema, nsid, config) {
                Ok(code) => {
                    all_row_types.push_str(&format!("// {nsid}\n"));
                    all_row_types.push_str(&code);
                }
                Err(e) => eprintln!("  warn: emit_row_types for {nsid}: {e}"),
            }

            // CRUD functions
            match emit_rows::emit_crud(&atproto_schema, nsid, config) {
                Ok(code) => {
                    all_crud.push_str(&format!("// {nsid}\npub mod {} {{\n    use super::*;\n\n", config.table_name));
                    // Indent the generated code inside the module
                    for line in code.lines() {
                        if line.is_empty() {
                            all_crud.push('\n');
                        } else {
                            all_crud.push_str("    ");
                            all_crud.push_str(line);
                            all_crud.push('\n');
                        }
                    }
                    all_crud.push_str("}\n\n");
                }
                Err(e) => eprintln!("  warn: emit_crud for {nsid}: {e}"),
            }

            // from_json deserializer
            match emit_rows::emit_from_json(&atproto_schema, nsid, config) {
                Ok(code) => {
                    all_from_json.push_str(&format!("// {nsid}\n"));
                    all_from_json.push_str(&code);
                }
                Err(e) => eprintln!("  warn: emit_from_json for {nsid}: {e}"),
            }
        }
    }

    // Write generated files (reference copies in generated/)
    fs::write(generated_dir.join("rust/types.rs"), &all_rust)?;
    fs::write(generated_dir.join("rust/row_types.rs"), &all_row_types)?;
    fs::write(generated_dir.join("rust/crud.rs"), &all_crud)?;
    fs::write(generated_dir.join("rust/from_json.rs"), &all_from_json)?;
    fs::write(generated_dir.join("sql/schema.sql"), &all_sql)?;
    fs::write(generated_dir.join("typescript/types.ts"), &all_ts)?;

    // Write appview-integrated copies
    let appview_gen_dir = workspace_root.join("crates/cospan-appview/src/db/generated");
    fs::create_dir_all(&appview_gen_dir)?;
    fs::write(appview_gen_dir.join("types.rs"), &all_row_types)?;
    fs::write(appview_gen_dir.join("crud.rs"), &all_crud)?;
    fs::write(appview_gen_dir.join("from_json.rs"), &all_from_json)?;
    fs::write(appview_gen_dir.join("mod.rs"), "\
// Generated by cospan-codegen — do not edit manually.

#[allow(dead_code, unused_imports)]
pub mod types;
#[allow(dead_code, unused_imports)]
pub mod crud;
#[allow(dead_code, unused_imports)]
pub mod from_json;

pub use types::*;
")?;

    // Save schema baseline for future --check runs
    let baseline: serde_json::Value = schemas_for_baseline
        .iter()
        .map(|(nsid, json)| (nsid.clone(), json.clone()))
        .collect::<serde_json::Map<String, serde_json::Value>>()
        .into();
    fs::write(
        generated_dir.join("sql/baseline.json"),
        serde_json::to_string_pretty(&baseline)?,
    )?;

    println!("\nGenerated:");
    println!("  generated/rust/types.rs                        (Lexicon record types)");
    println!("  generated/rust/row_types.rs                    (database Row types)");
    println!("  generated/rust/crud.rs                         (CRUD functions)");
    println!("  generated/rust/from_json.rs                    (Jetstream deserializers)");
    println!("  generated/sql/schema.sql                       (PostgreSQL DDL)");
    println!("  generated/sql/baseline.json                    (schema baseline for --check)");
    println!("  generated/typescript/types.ts                  (TypeScript interfaces)");
    println!("  crates/cospan-appview/src/db/generated/        (appview integration)");

    Ok(())
}

/// Check mode: compare current Lexicons against baseline for breaking changes.
fn run_check_mode(
    lexicon_files: &[PathBuf],
    _lexicons_dir: &Path,
    generated_dir: &Path,
) -> Result<()> {
    let baseline_path = generated_dir.join("sql/baseline.json");
    if !baseline_path.exists() {
        println!("No baseline found at {}. Run codegen first to create it.", baseline_path.display());
        println!("  cargo run -p cospan-codegen");
        return Ok(());
    }

    let baseline_str = fs::read_to_string(&baseline_path)?;
    let baseline: serde_json::Value = serde_json::from_str(&baseline_str)?;
    let baseline_map = baseline.as_object().expect("baseline must be an object");

    let protocol = panproto_schema::Protocol::default();
    let mut breaking_found = false;

    for lexicon_path in lexicon_files {
        let json_str = fs::read_to_string(lexicon_path)?;
        let json: serde_json::Value = serde_json::from_str(&json_str)?;
        let nsid = json.get("id").and_then(|v| v.as_str()).unwrap_or("unknown");

        if let Some(old_json) = baseline_map.get(nsid) {
            let old_schema = atproto::parse_lexicon(old_json);
            let new_schema = atproto::parse_lexicon(&json);

            if let (Ok(old), Ok(new)) = (old_schema, new_schema) {
                let diff = panproto_check::diff(&old, &new);
                let report = panproto_check::classify(&diff, &protocol);

                if !report.breaking.is_empty() {
                    breaking_found = true;
                    eprintln!("BREAKING: {nsid}");
                    eprintln!("{}", panproto_check::report_text(&report));
                }
            }
        } else {
            println!("  NEW: {nsid} (not in baseline)");
        }
    }

    if breaking_found {
        eprintln!("\nBreaking changes detected! Run codegen to update baseline.");
        std::process::exit(1);
    } else {
        println!("No breaking changes detected.");
    }

    Ok(())
}

fn discover_lexicons(dir: &Path) -> Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    walk_dir(dir, &mut files)?;
    files.sort();
    Ok(files)
}

fn walk_dir(dir: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    if !dir.exists() {
        anyhow::bail!("lexicons directory not found: {}", dir.display());
    }
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            walk_dir(&path, files)?;
        } else if path.extension().is_some_and(|e| e == "json") {
            files.push(path);
        }
    }
    Ok(())
}

fn find_workspace_root() -> Result<PathBuf> {
    let mut dir = std::env::current_dir()?;
    loop {
        if dir.join("Cargo.toml").exists() && dir.join("packages").exists() {
            return Ok(dir);
        }
        if !dir.pop() {
            anyhow::bail!("could not find workspace root (looking for Cargo.toml + packages/)");
        }
    }
}
